### ISSUE TITLE
Make library aliases work with fully qualified symbols

### ISSUE THREAD

**Issue by borkdude** [borkdude/nbb#11]
E.g.:

``` clojure
(ns foo.script
  (:require ["fs" :as fs]))
(println (count (str (fs/readFileSync "script.cljs"))))
```

Does normal CLJS create a "real" namespace for fs or is fs just the fs object from the library itself? And is fs/readFileSync then translated into an object lookup in this library, or is there a "real" namespace with a readFileSync function created behind the scenes?
It seems like it's doing something like the latter (with lumo):
cljs.user=> (str (fn [] (fs/readFileSync "script.cljs")))
"function (){\nreturn cljs.user.node$module$fs.readFileSync.call(null,\"script.cljs\");\n}"

Interesting bits from CLJS

- https://github.com/clojure/clojurescript/blob/c0045c5718014f4cc40db55742140d2eb561807c/src/main/clojure/cljs/analyzer.cljc#L795
- https://github.com/clojure/clojurescript/blob/c0045c5718014f4cc40db55742140d2eb561807c/src/main/clojure/cljs/analyzer.cljc#L1129-L1132

**Comment by thheller** [comment]
FWIW In shadow-cljs the `"fs"` is first converted to a pseudo namespace which looks like a regular `goog.provide`.

So `"fs"` becomes `shadow.js.shim.module$fs` which is then just

```
goog.provide("shadow.js.shim.module$fs");
shadow.js.shim.module$fs = require("fs");
```

So in essence this becomes a "real" google closure namespace which all CLJS namespaces are effectively as well. It fits right in, no more extra treatment in the code elsewhere. Effectively `(:require ["fs" :as fs])` is converted to `(:require [shadow.js.shim.module$fs :as fs])` and that new extra ns is created dynamically once, even if many namespaces require `"fs"`.

This is quite different from what regular CLJS does though, which creates a special object and require for every "require". I implemented it this way to effectively limit the generated `require("fs")` to once only. Reduces duplication and looks cleaner IMHO.
