### ISSUE TITLE
Which style of requires should be support: cjs or esm style?

### ISSUE THREAD

**Issue by borkdude** [borkdude/nbb#14]
@thheller: if you have an opinion on this, hearing it would be most interesting. I'm aware of the `foo$default` vs `"foo" :default foo` syntax, that's not what this issue is about, when I write `:default` below, just assume I mean the dollar syntax.

/cc @filipesilva

<img width="771" alt="Screenshot 2021-08-01 at 18 27 49" src="https://user-images.githubusercontent.com/284934/127778326-9e2219e5-dd93-4529-b3c5-b55182334720.png">

**Comment by thheller** [comment]
It entirely depends on what the library returns when you "require" it. shadow-cljs does no further handling, detection or "magic rewrites". You get what you what the library gives you. There is never any rewriting of any kind. CLJS has something like that I can't remember, shadow-cljs definitely does not.

Once more packages move to ESM it'll become quite common for builds to break since `:default` or `thing$default` will become far more common. Thats just the usual churn in JS land though and I'll absolutely not add magic detection for any of this in shadow-cljs.

**Comment by borkdude** [comment]
@thheller 

The thing is, now I'm passing these strings to the require function from `createRequire` (not further processing) and this does "the right thing" when you use `["shelljs" :as sh]` so you can call `(sh/ls "foo")` etc. 

But when processing the string with `shadow.esm/dynamic-import`, this becomes `["shelljs$default" :as sh]` which is a bit more verbose (the dollar is something which will be supported, not yet there, but `:default sh`, although undocumented, still works).

Building `nbb`'s `require` of node modules on top of `createRequire` has the benefit that requires are more succinct and more familiar to what CLJS users already did in node before (probably). It has the disadvantage that you cannot load ESM modules with it.

Building `require` on top of ESM has the disadvantage (currently) that there is no such resolving as with `createRequire` (although there is `import.meta.resolve` which I haven't gotten to work with CLJS) and that the lib names are longer (with the `$default` suffix.

**Comment by borkdude** [comment]
Perhaps `nbb` should just have a global switch so the user can choose...?

**Comment by filipesilva** [comment]
I think this is the relevant part of the shadow-cljs user guide: https://shadow-cljs.github.io/docs/UsersGuide.html#js-entry-keys
> Interop between CommonJS and ESM can be tricky so shadow-cljs defaults to using CommonJS but it can be beneficial to use ESM.
> ...
> You can configure shadow-cljs to prefer the module entry via the :entry-keys JS option. It takes a vector of string keys found in package.json which will be tried in order. The default is "["browser" "main" "module"].

The other relevant part here is that packages will list entry points. Commonly `main` for CommonJS and sometimes `module` for ESM, but nothing enforces it so you can also just have `main` and it's actually ESM. Shadow-CLJS just gives you what's in `main` by default but lets you configure it to get what's in `module` first if it exists, but it's always using `require`.

I ran a test in js to see what the deal is with shelljs. It only list `main` and that points to a CommonJS module.

```
// ./src/script.mjs
import shelljs from 'shelljs';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);

console.log("require")
console.log(Object.keys(require("shelljs")));

console.log("static import")
console.log(Object.keys(shelljs));

console.log("dynamic import")
import("shelljs").then(x => console.log(Object.keys(x)))
```

This outputs:
```
require
[
  'cat',   'cd',     'chmod',
  'cp',    'dirs',   'pushd',
  'popd',  'echo',   'tempdir',
  'pwd',   'exec',   'ls',
  'find',  'grep',   'head',
  'ln',    'mkdir',  'rm',
  'mv',    'sed',    'set',
  'sort',  'tail',   'test',
  'touch', 'uniq',   'which',
  'exit',  'error',  'ShellString',
  'env',   'config'
]
static import
[
  'cat',   'cd',     'chmod',
  'cp',    'dirs',   'pushd',
  'popd',  'echo',   'tempdir',
  'pwd',   'exec',   'ls',
  'find',  'grep',   'head',
  'ln',    'mkdir',  'rm',
  'mv',    'sed',    'set',
  'sort',  'tail',   'test',
  'touch', 'uniq',   'which',
  'exit',  'error',  'ShellString',
  'env',   'config'
]
dynamic import
[ 'ShellString', 'config', 'default', 'env', 'error', 'exit' ]
```
 
So importing this CommonJS module with both `require` and static `import` gives the same result, but using the dynamic `import` gives something different. For the semantics of cljs require, I think it should either be the same as CommonJS require or ESM static import, but never ESM dynamic import.

I think the conclusion here is that ESM static and dynamic imports do not return the same thing and shouldn't be used interchangeably. I thought they did.

**Comment by thheller** [comment]
You really really shouldn't mix `import` and `require` in any system. Pick one. Or you end up in CommonJS <-> ESM interop nightmares. For what you are doing you probably want to stay in CommonJS land since `require` is much more dynamic and a little more convenient to use overall.

ESM in my opinion is not "there yet" and I don't know how long it'll take to get there. Many packages such as `react` still don't ship any ESM at all since it is more limiting in what it lets you do. Much like the limitations CLJS has with `(require ...)` vs CLJ.

**Comment by borkdude** [comment]
@thheller Thank you for your comment. I will stay on the require path then. Dynamic import is exposed as `js/import` (backed by `shadow.esm/dynamic-import`) for those who want to use it.

**Comment by borkdude** [comment]
@filipesilva If I understand this correctly (from: https://github.com/nodejs/help/issues/3131):

```
import m1 from 'data:text/javascript,let a = {x: 1}; export default a;';

(async function main() {
  const m2 = await import ('data:text/javascript,let a = {x: 1}; export default a;');
  console.log(m1);
  console.log(m2);
})();

// { x: 1 }
// [Module] { default: { x: 1 } }
```

then `import from x from ...` means that `x` _is_ the default object. You can get the entire module with default inside of it, by writing: `import * as x from ...` (from: https://stackoverflow.com/questions/65379477/why-are-static-and-dynamic-imports-in-node-js-treated-differently-wrt-read-only).

**Comment by filipesilva** [comment]
That's a nice way to look at it, that the dynamic import implicitly gives you the whole thing as if you had imported statically with `* as x`. Thinking of it that way it's pretty obvious that the dynamic import had to use some specifier and that * is the most general.

**Comment by borkdude** [comment]
I had to switch to ESM-style anyway since some packages only distribute as ESM now, like `term-size` and `zx`. Breaking change, but this allows using more libraries. 

Example:

``` clojure
(ns script
  (:require ["csv-parse/lib/sync$default" :as csv-parse]
            ["fs" :as fs]
            ["shelljs$default" :as sh]
            ["zx$fs" :as zxfs]
            [nbb.core :refer [*file*]]))

(println (count (str (fs/readFileSync "script.cljs"))))

(prn (sh/ls "."))

(prn (csv-parse "foo,bar"))

(prn (zxfs/existsSync *file*))
```
