### ISSUE TITLE
Rationale? Why nbb if there's already other similar tools? 

### ISSUE THREAD

**Issue by glyh** [borkdude/nbb#15]
For example, there's planck, a standalone CLJS REPL, that compiles to C.

**Comment by borkdude** [comment]
Well, for example, Planck doesn't give you access to the NodeJS ecosystem which nbb is specifically made for (or is going to be made for). Btw, Planck does not compile to C, it's just self-hosted ClojureScript: so the ClojureScript you type, is compiled to JavaScript.

Moreover, the idea of this tool is more in the way babashka works: a tool with pre-bundled utilities for scripting which allows you to create useful scripts without a lot of project setup first or JVM tooling. You can always migrate to that but for getting started, `nbb` might offer you a quicker way to get going.
It's still early days, but one of the optional modules for example is `reagent.core`, which can be used for creating TUI apps with Ink.

**Comment by borkdude** [comment]
I wrote this on Reddit:

> Similar goals as babashka but not replacing bash by Clojure, but tapping into the Node.js ecosystem without having to write JS (instead, we write CLJS). No or little project setup cost but still the flexibility of migrating to a full blown (shadow-)CLJS project later if you want to use a compiled, more performant version of your script. Built-in goodies like reagent for building TUIs. I don't have a set-in-stone vision for this project, that's why it's currently marked as experimental. I don't see it as a replacement for babashka, but as an additional way to use Clojure/Script for scripting. When somebody asks in the babashka channel, can I use bb to extract data from Excel sheets, I might recommend nbb if Node.js has a good library for this.

**Comment by chr15m** [comment]
@borkdude I've tried both `planck` and `cljs-lumo` in the past. `nbb` is the first time I've been able to just write idiomatic Node/ClojureScript code and have it do what I expect with regards to importing libraries etc. Thank you so much for making this. :pray:

**Comment by borkdude** [comment]
@chr15m Thanks. I've now also made React optional (as it should be picked up from ink, etc, when you install it), yielding only 1.2mb. We could even make the reagent module part of another npm package `nbb-reagent` or so, but this is only 30kb, which is pretty small compared to the rest, so I guess it's ok for now.

**Comment by borkdude** [comment]
I tried summarizing the above in https://github.com/borkdude/nbb#goals.
