### ISSUE TITLE
Expose globals __filename and __dirname for the cljs file being executed

### ISSUE THREAD

**Issue by chr15m** [borkdude/nbb#32]
Node users are used to having these around. https://nodejs.org/api/modules.html#modules_filename

In `wisp` and `cljs-lumo` these are available via `js/__filename`.

**Comment by borkdude** [comment]
@chr15m I chose to expose this under the more Clojure-esque `*file*` dynamic var which SCI already has. I just had to integrate it with nbb. This var is available under `nbb.core/*file*` (to not confuse static linters like clj-kondo that don't expect `*file*` to be part of CLJS) and also there is a `:file` key on the metadata of vars.

``` clojure
(ns foo
  (:require [nbb.core :refer [*file*]]))

(prn *file*) ;; "/private/tmp/foo.cljs"

(defn f [])
(prn (:file (meta #'f))) ;; "/private/tmp/foo.cljs"
```
