### ISSUE TITLE
Support clojure.test

### ISSUE THREAD

**Issue by borkdude** [borkdude/nbb#41]
This will be handy for writing browser tests with puppeteer or https://github.com/microsoft/playwright

**Comment by ErikSchierboom** [comment]
It would be great if this were supported.

**Comment by borkdude** [comment]
Coming soon :)

**Comment by ErikSchierboom** [comment]
Fantastic news!

**Comment by borkdude** [comment]
@ErikSchierboom The first version of `clojure.test` is now available.

```
$ cat test.cljs
(ns foo (:require [clojure.test :as t :refer [deftest async]]))

(deftest foo
  (async done
         (js/setTimeout #(do (t/is (= 1 2)) (done)) 5000)))

(t/run-tests 'foo)
$ nbb test.cljs

Testing foo

FAIL in (foo) (:5)
expected: (= 1 2)
  actual: (not (= 1 2))

Ran 1 tests containing 1 assertions.
1 failures, 0 errors.
```

I'm planning to support more compatibility with the original CLJS test so please keep the issues coming if you discover something that isn't working as the original CLJS.

**Comment by ErikSchierboom** [comment]
@borkdude Cool! I'll be testing it.

**Comment by ErikSchierboom** [comment]
@borkdude Looks to be working well!

**Comment by ErikSchierboom** [comment]
@borkdude One thing I noticed was that if only some tests fail (not all), the exit code is `0`. I think this should be `1`. Am I doing something wrong?

**Comment by borkdude** [comment]
That's a good point. Normally `clojure.test` doesn't do anything with the exit code and you should inspect the test results to do that.

In the cljs.test docs about `run-tests`:

> Runs all tests in the given namespaces; prints results.
Defaults to current namespace if none given. Does not return a meaningful
value due to the possiblity of asynchronous execution. To detect test
completion add a :end-run-tests method case to the cljs.test/report
multimethod.

So I think we should support this as the next step. I'll make an issue.
