### ISSUE TITLE
(js/import "module") doesn't work when using global ver of nbb

### ISSUE THREAD

**Issue by huygn** [borkdude/nbb#46]
Just found out that `(js/import "module")` won't work with global `nbb`, but works if I've installed local `nbb` but running using global `nbb`.

For example this will work:
```sh
yarn global add nbb
yarn add nbb term-size
# uses (js/import "term-size") in script.cljs
nbb script.cljs
```

This will not work:
```sh
yarn global add nbb
yarn add term-size
# uses (js/import "term-size") in script.cljs
nbb script.cljs
# Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'term-size' imported from /Users/macair/.volta/tools/image/packages/nbb/lib/node_modules/nbb/out/nbb_core.js
```

**Comment by borkdude** [comment]
Can you make a more complete repro with the actual script.cljs you're trying to run? E.g. I don't understand if you're literally trying to import `"module"` or if this is an example name. More details is better.

**Comment by huygn** [comment]
I've edited, will include a reproc file soon

**Comment by borkdude** [comment]
Should work with nbb 0.0.50! Note that we're now always using ESM import so you might have to suffix some lib names with `$default` whereas previous you would not, but at least this works now with all libs.

**Comment by alexandercarls** [comment]
@borkdude Not sure if I should create a new issue or not.

I think there was a regression or I am confused with node modules imports again.

I created a reproduction here: https://github.com/alexandercarls/repro-nbb-dynamic-import/blob/main/script.cljs

```clojure
(ns script
  (:require [nbb.core :refer [await]]))

;; Possible regression of #46

;; Doesn't work. nbb looks at the global node_modules folder first instead
;; of the relative one
;; when running with `nbb script.cljs`.

;; If you run `npm run test` (invokes locally installed nbb) it works.

;; If you remove locally installed nbb `npm uninstall nbb`,
;; the REPL doesn't work when evaluating the form (tested via Calva)
;; as it also doesn't resolve from the local node_modules folder

(def handle-term-size (await (js/import "term-size"))) ; ES-Module

;; This CommonJS Module can be loaded via 'require' just fine with local nbb and global nbb
(def handle-prismjs (js/require "prismjs/components/")) ; CommonJS Module

(prn (type handle-prismjs)) ;; #object[Function]
(prn (handle-term-size.default))
```

I quickly verified that Node.js `node` resolves imported libraries relatively to the file.
e.g. `node some/folder/repo/index.mjs` resolved dependencies in `repo`.

**Comment by borkdude** [comment]
@alexandercarls Why do you use dynamic import / require?
