### ISSUE TITLE
Support server side rendering with reagent.dom.server

### ISSUE THREAD

**Issue by chr15m** [borkdude/nbb#68]
A pattern I am using in cljs web servers is to use Reagent's render-to-static-markup and inject the result into my template to be returned:

```clojure
(:require [reagent.dom.server :refer [render-to-static-markup] :rename {render-to-static-markup r}])

;...

(aset template "innerHTML" (r [:div "My response]))
```

(where template here is an instance of node-html-parser on the server side)

This currently throws and error in nbb:

```
$ npx nbb myserver.cljs

> @ serve /home/chrism/dev/sitefox/examples/nbb
> nbb --classpath ../../src/ webserver.clj

----- Error --------------------------------------
Message:  No namespace: reagent.dom.server
```

Would be great to have access to reagent.dom.server!

**Comment by borkdude** [comment]
Coming up in v0.0.88
