### ISSUE TITLE
Support `:end-run-tests` multi-method for cljs.test

### ISSUE THREAD

**Issue by borkdude** [borkdude/nbb#74]
That's a good point. Normally `clojure.test` doesn't do anything with the exit code and you should inspect the test results to do that.

In the cljs.test docs about `run-tests`:

> Runs all tests in the given namespaces; prints results.
Defaults to current namespace if none given. Does not return a meaningful
value due to the possiblity of asynchronous execution. To detect test
completion add a :end-run-tests method case to the cljs.test/report
multimethod.

So I think we should support this as the next step. I'll make an issue.

_Originally posted by @borkdude in https://github.com/borkdude/nbb/issues/41#issuecomment-935800184_

/cc @ErikSchierboom

**Comment by borkdude** [comment]
Pushing `v0.0.92` where this is supported:

``` clojure
(ns foo (:require [clojure.test :as t :refer [deftest async]]))

(deftest foo
  (async done
         (js/setTimeout #(do (t/is (= 1 2)) (done)) 1000)))

(defmethod t/report [:cljs.test/default :end-run-tests] [{:keys [fail error]}]
  (js/process.exit (if (pos? (+ fail error))
                     1
                     0)))

(t/run-tests 'foo)
```

That will exit the script with exit code 1.

**Comment by ErikSchierboom** [comment]
Yep, that works. Thanks!
