### ISSUE TITLE
Ability to run code before repl is started

### ISSUE THREAD

**Issue by chr15m** [borkdude/nbb#89]
Sometimes it's nice to launch a repl with some requires or functions already defined. This allows us to use nbb as a quick starting DSL for various use cases. An example would be requiring zx and launching the repl so the user can immediately start doing shell type of things. Another example might be pre-configuring an SSH library for remote work.

Potential interface could be a `-r` flag which drops into the repl after normal execution. E.g.

```
nbb -r pre-require.cljs
```

```
nbb -r -e '(ns script (:require ["fs" :as fs]))'
```

**Comment by borkdude** [comment]
One alternative to this could be to launch the REPL from a script:

```
nbb script.cljs
```
where scripts.cljs contains:

```
(ns script (:require ["fs" :as fs] [nbb.repl :as repl))
(repl/repl {})
```

**Comment by chr15m** [comment]
Ha ha ok sorry. Yes that looks like it would satisfy the use-case cleanly.
